-- Table: etc.e_shopify

-- DROP TABLE IF EXISTS etc.e_shopify;

CREATE TABLE IF NOT EXISTS etc.e_shopify
(
    running_id integer NOT NULL DEFAULT nextval('etc.elittile_shopify_id_seq'::regclass),
    product_id character varying COLLATE pg_catalog."default",
    shopify_id character varying COLLATE pg_catalog."default",
    handle character varying COLLATE pg_catalog."default",
    command character varying COLLATE pg_catalog."default",
    title character varying COLLATE pg_catalog."default",
    body_html character varying COLLATE pg_catalog."default",
    vendor character varying COLLATE pg_catalog."default",
    type character varying COLLATE pg_catalog."default",
    tags character varying COLLATE pg_catalog."default",
    tags_command character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    status character varying COLLATE pg_catalog."default",
    published boolean,
    published_at timestamp without time zone,
    published_scope character varying COLLATE pg_catalog."default",
    template_suffix character varying COLLATE pg_catalog."default",
    gift_card boolean,
    url character varying COLLATE pg_catalog."default",
    total_inventory_qty numeric,
    row_num numeric,
    top_row boolean,
    category_id character varying COLLATE pg_catalog."default",
    category_name character varying COLLATE pg_catalog."default",
    category character varying COLLATE pg_catalog."default",
    custom_collections character varying COLLATE pg_catalog."default",
    smart_collections character varying COLLATE pg_catalog."default",
    image_type character varying COLLATE pg_catalog."default",
    image_src character varying COLLATE pg_catalog."default",
    image_command character varying COLLATE pg_catalog."default",
    image_position numeric,
    image_width numeric,
    image_height numeric,
    image_alt_text character varying COLLATE pg_catalog."default",
    variant_inventory_item_id character varying COLLATE pg_catalog."default",
    variant_id character varying COLLATE pg_catalog."default",
    variant_command character varying COLLATE pg_catalog."default",
    option1_name character varying COLLATE pg_catalog."default",
    option1_value character varying COLLATE pg_catalog."default",
    option2_name character varying COLLATE pg_catalog."default",
    option2_value character varying COLLATE pg_catalog."default",
    option3_name character varying COLLATE pg_catalog."default",
    option3_value character varying COLLATE pg_catalog."default",
    variant_position numeric,
    variant_sku character varying COLLATE pg_catalog."default",
    variant_barcode character varying COLLATE pg_catalog."default",
    variant_image character varying COLLATE pg_catalog."default",
    variant_weight double precision,
    variant_weight_unit character varying COLLATE pg_catalog."default",
    variant_price double precision,
    variant_compare_at_price character varying COLLATE pg_catalog."default",
    variant_taxable character varying COLLATE pg_catalog."default",
    variant_tax_code character varying COLLATE pg_catalog."default",
    variant_inventory_tracker character varying COLLATE pg_catalog."default",
    variant_inventory_policy character varying COLLATE pg_catalog."default",
    variant_fulfillment_service character varying COLLATE pg_catalog."default",
    variant_requires_shipping character varying COLLATE pg_catalog."default",
    variant_inventory_qty numeric,
    variant_inventory_adjust character varying COLLATE pg_catalog."default",
    variant_cost double precision,
    variant_hs_code character varying COLLATE pg_catalog."default",
    variant_country_of_origin character varying COLLATE pg_catalog."default",
    variant_province_of_origin character varying COLLATE pg_catalog."default",
    inventory_available_12555_sherman_way character varying COLLATE pg_catalog."default",
    inventory_available_4677_w_pico_blvd character varying COLLATE pg_catalog."default",
    inventory_available_adjust_12555_sherman_way character varying COLLATE pg_catalog."default",
    inventory_available_adjust_4677_w_pico_blvd character varying COLLATE pg_catalog."default",
    metafield_title_tag_string character varying COLLATE pg_catalog."default",
    metafield_description_tag_string character varying COLLATE pg_catalog."default",
    variant_metafield_pricelist_cost_by_uom_number_decimal double precision,
    variant_metafield_pricelist_uom_single_line_text_field character varying COLLATE pg_catalog."default",
    variant_metafield_calculator_show_for_variant_boolean boolean,
    variant_metafield_calculator_ratio_number_decimal double precision,
    variant_metafield_pricelist_ea_bx_number_integer numeric,
    variant_metafield_pricelist_sell_unit_single_line_text_field character varying COLLATE pg_catalog."default",
    variant_metafield_pricelist_msrp_uom_number_decimal double precision,
    variant_metafield_pricelist_msrp_sell_unit_number_decimal double precision,
    variant_metafield_pricelist_class_single_line_text_field character varying COLLATE pg_catalog."default",
    variant_metafield_pricelist_vendor_code_single_line_text_field character varying COLLATE pg_catalog."default",
    variant_metafield_custom_retail_v_code_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_my_fields_sq_price_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_custom_multi_line_pack_info_multi_line_text_field character varying COLLATE pg_catalog."default",
    metafield_filter_look_list_single_line_text_field text COLLATE pg_catalog."default",
    metafield_filter_application_list_single_line_text_field text COLLATE pg_catalog."default",
    metafield_filter_material_list_single_line_text_field text COLLATE pg_catalog."default",
    metafield_filter_color_list_single_line_text_field text COLLATE pg_catalog."default",
    metafield_filter_piece_type_single_line_text_field text COLLATE pg_catalog."default",
    metafield_pricelist_filter_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_filter_size_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_filter__list_single_line_text_field text COLLATE pg_catalog."default",
    metafield_calculator_show_boolean boolean,
    metafield_custom_custom_variant_collection_reference character varying COLLATE pg_catalog."default",
    metafield_tile_filter_tile_shape_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tile_filter_trim_type_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tile_filter_primary_application_single_line_text_fiel character varying COLLATE pg_catalog."default",
    metafield_custom_series_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tile_filter_commercial_application_list_single_line_t text COLLATE pg_catalog."default",
    metafield_sample_sku_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_custom_sample_product_product_reference character varying COLLATE pg_catalog."default",
    variant_metafield_pricelist_sf_box_number_decimal double precision,
    variant_metafield_pricelist_sf_ea_number_decimal double precision,
    metafield_tile_filter_mosaic_shape_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_custom_material_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_filter_commercial_application_list_single_line_text_f character varying COLLATE pg_catalog."default",
    metafield_tile_filter_format_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tile_filter_other_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tile_filter_thickness_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_metal_trim_thickness_single_line_text_fie character varying COLLATE pg_catalog."default",
    metafield_tool_filter_metal_trim_finish_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_metal_trim_length_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_type_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_tools_categories_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_calculator_ratio_number_decimal double precision,
    variant_metafield_custom_limited_stock_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_size_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_application_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_finish_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_look_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_base_color_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_volume_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_my_fields_brand_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_tile_spacer_shape_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_tile_spacer_size_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_blade_cut_material_list_single_line_text_ character varying COLLATE pg_catalog."default",
    metafield_tool_filter_blade_material_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_grout_base_color_list_single_line_text_fi character varying COLLATE pg_catalog."default",
    metafield_tool_filter_grout_type_list_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_custom_trowel_notch_type_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_tool_filter_trowel_size_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_pricelist_finish_single_line_text_field character varying COLLATE pg_catalog."default",
    metafield_custom_parent_product_product_reference character varying COLLATE pg_catalog."default",
    metafield_seo_hidden_number_integer numeric,
    metafield_sample_skus_list_single_line_text_field character varying COLLATE pg_catalog."default",
    filename character varying COLLATE pg_catalog."default",
    load_id uuid,
    date_upload timestamp without time zone,
    uploaded_by character varying COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS etc.e_shopify
    OWNER to "DUser";