-- Table: etc.load_all_load

-- DROP TABLE IF EXISTS etc.load_all_load;

CREATE TABLE IF NOT EXISTS etc.load_all_load
(
    externalid character varying COLLATE pg_catalog."default",
    itemid character varying COLLATE pg_catalog."default",
    displayname character varying COLLATE pg_catalog."default",
    item_name character varying COLLATE pg_catalog."default",
    item_number_and_name character varying COLLATE pg_catalog."default",
    vendor_name_code character varying COLLATE pg_catalog."default",
    salesdescription character varying COLLATE pg_catalog."default",
    sales_packaging_unit character varying COLLATE pg_catalog."default",
    sales_qty_per_pack_unit double precision,
    item_color character varying COLLATE pg_catalog."default",
    item_size character varying COLLATE pg_catalog."default",
    pcs_in_a_box numeric,
    sqft_by_pcssheet character varying COLLATE pg_catalog."default",
    sqft_by_box double precision,
    price_by_uom double precision,
    unitstype character varying COLLATE pg_catalog."default",
    stockunit character varying COLLATE pg_catalog."default",
    purchaseunit character varying COLLATE pg_catalog."default",
    saleunits character varying COLLATE pg_catalog."default",
    parent character varying COLLATE pg_catalog."default",
    subsidiary character varying COLLATE pg_catalog."default",
    includechildren character varying COLLATE pg_catalog."default",
    department character varying COLLATE pg_catalog."default",
    class numeric,
    location character varying COLLATE pg_catalog."default",
    costingmethod character varying COLLATE pg_catalog."default",
    cost double precision,
    purchasedescription character varying COLLATE pg_catalog."default",
    stockdescription character varying COLLATE pg_catalog."default",
    matchbilltoreceipt character varying COLLATE pg_catalog."default",
    usebins character varying COLLATE pg_catalog."default",
    supplyreplenishmentmethod character varying COLLATE pg_catalog."default",
    alternatedemandsourceitem character varying COLLATE pg_catalog."default",
    autopreferredstocklevel character varying COLLATE pg_catalog."default",
    reordermultiple character varying COLLATE pg_catalog."default",
    isspecialorderitem character varying COLLATE pg_catalog."default",
    autoreorderpoint character varying COLLATE pg_catalog."default",
    autoleadtime character varying COLLATE pg_catalog."default",
    leadtime character varying COLLATE pg_catalog."default",
    safetystocklevel character varying COLLATE pg_catalog."default",
    safetystockleveldays character varying COLLATE pg_catalog."default",
    transferprice character varying COLLATE pg_catalog."default",
    preferredlocation character varying COLLATE pg_catalog."default",
    itembinnumber1 character varying COLLATE pg_catalog."default",
    preferredperlocation character varying COLLATE pg_catalog."default",
    vendor1_name character varying COLLATE pg_catalog."default",
    vendor1_subsidiary numeric,
    vendor1_preferred boolean,
    vendor1_purchaseprice double precision,
    vendor1_schedule character varying COLLATE pg_catalog."default",
    vendor1_code character varying COLLATE pg_catalog."default",
    vendor2_name character varying COLLATE pg_catalog."default",
    vendor2_subsidiary numeric,
    vendor2_preferred boolean,
    vendor2_purchaseprice double precision,
    vendor2_code character varying COLLATE pg_catalog."default",
    itemlocationline1_location character varying COLLATE pg_catalog."default",
    itemlocationline1_defaultreturncost character varying COLLATE pg_catalog."default",
    itemlocationline1_preferredstocklevel character varying COLLATE pg_catalog."default",
    itemlocationline1_reorderpoint character varying COLLATE pg_catalog."default",
    itemlocationline1_lotnumbers character varying COLLATE pg_catalog."default",
    itemlocationline1_lotsizingmethod character varying COLLATE pg_catalog."default",
    costestimatetype character varying COLLATE pg_catalog."default",
    costestimate character varying COLLATE pg_catalog."default",
    minimumquantity character varying COLLATE pg_catalog."default",
    enforceminqtyinternally character varying COLLATE pg_catalog."default",
    itempriceline1_itempricetyperef character varying COLLATE pg_catalog."default",
    itempriceline1_itemprice double precision,
    itempriceline1_quantitypricing numeric,
    cogsaccount character varying COLLATE pg_catalog."default",
    incomeaccount character varying COLLATE pg_catalog."default",
    assetaccount character varying COLLATE pg_catalog."default",
    billpricevarianceacct character varying COLLATE pg_catalog."default",
    billqtyvarianceacct character varying COLLATE pg_catalog."default",
    billexchratevarianceacct character varying COLLATE pg_catalog."default",
    custreturnvarianceaccount character varying COLLATE pg_catalog."default",
    vendreturnvarianceaccount character varying COLLATE pg_catalog."default",
    taxschedule character varying COLLATE pg_catalog."default",
    product_id character varying COLLATE pg_catalog."default",
    internalid character varying COLLATE pg_catalog."default",
    filename character varying COLLATE pg_catalog."default",
    load_id uuid,
    date_upload timestamp without time zone,
    uploaded_by character varying COLLATE pg_catalog."default",
    running_id integer NOT NULL DEFAULT nextval('etc.load_all_load_running_id_seq'::regclass)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS etc.load_all_load
    OWNER to "DUser";