-- Table: etc.load_staging

-- DROP TABLE IF EXISTS etc.load_staging;

CREATE TABLE IF NOT EXISTS etc.load_staging
(
    externalid character varying COLLATE pg_catalog."default",
    itemid character varying COLLATE pg_catalog."default",
    displayname character varying COLLATE pg_catalog."default",
    item_name character varying COLLATE pg_catalog."default",
    item_number_and_name character varying COLLATE pg_catalog."default",
    vendor_name_code character varying COLLATE pg_catalog."default",
    salesdescription character varying COLLATE pg_catalog."default",
    sales_packaging_unit character varying COLLATE pg_catalog."default",
    sales_qty_per_pack_unit character varying COLLATE pg_catalog."default",
    item_color character varying COLLATE pg_catalog."default",
    item_size character varying COLLATE pg_catalog."default",
    pcs_in_a_box character varying COLLATE pg_catalog."default",
    sqft_by_pcssheet character varying COLLATE pg_catalog."default",
    sqft_by_box character varying COLLATE pg_catalog."default",
    price_by_uom character varying COLLATE pg_catalog."default",
    unitstype character varying COLLATE pg_catalog."default",
    stockunit character varying COLLATE pg_catalog."default",
    purchaseunit character varying COLLATE pg_catalog."default",
    saleunits character varying COLLATE pg_catalog."default",
    parent character varying COLLATE pg_catalog."default",
    subsidiary character varying COLLATE pg_catalog."default",
    includechildren character varying COLLATE pg_catalog."default",
    department character varying COLLATE pg_catalog."default",
    class character varying COLLATE pg_catalog."default",
    location character varying COLLATE pg_catalog."default",
    costingmethod character varying COLLATE pg_catalog."default",
    cost character varying COLLATE pg_catalog."default",
    purchasedescription character varying COLLATE pg_catalog."default",
    stockdescription character varying COLLATE pg_catalog."default",
    matchbilltoreceipt character varying COLLATE pg_catalog."default",
    usebins character varying COLLATE pg_catalog."default",
    supplyreplenishmentmethod character varying COLLATE pg_catalog."default",
    alternatedemandsourceitem character varying COLLATE pg_catalog."default",
    autopreferredstocklevel character varying COLLATE pg_catalog."default",
    reordermultiple character varying COLLATE pg_catalog."default",
    isspecialorderitem character varying COLLATE pg_catalog."default",
    autoreorderpoint character varying COLLATE pg_catalog."default",
    autoleadtime character varying COLLATE pg_catalog."default",
    leadtime character varying COLLATE pg_catalog."default",
    safetystocklevel character varying COLLATE pg_catalog."default",
    safetystockleveldays character varying COLLATE pg_catalog."default",
    transferprice character varying COLLATE pg_catalog."default",
    preferredlocation character varying COLLATE pg_catalog."default",
    itembinnumber1 character varying COLLATE pg_catalog."default",
    preferredperlocation character varying COLLATE pg_catalog."default",
    vendor1_name character varying COLLATE pg_catalog."default",
    vendor1_subsidiary character varying COLLATE pg_catalog."default",
    vendor1_preferred character varying COLLATE pg_catalog."default",
    vendor1_purchaseprice character varying COLLATE pg_catalog."default",
    vendor1_schedule character varying COLLATE pg_catalog."default",
    vendor1_code character varying COLLATE pg_catalog."default",
    vendor2_name character varying COLLATE pg_catalog."default",
    vendor2_subsidiary character varying COLLATE pg_catalog."default",
    vendor2_preferred character varying COLLATE pg_catalog."default",
    vendor2_purchaseprice character varying COLLATE pg_catalog."default",
    vendor2_code character varying COLLATE pg_catalog."default",
    itemlocationline1_location character varying COLLATE pg_catalog."default",
    itemlocationline1_defaultreturncost character varying COLLATE pg_catalog."default",
    itemlocationline1_preferredstocklevel character varying COLLATE pg_catalog."default",
    itemlocationline1_reorderpoint character varying COLLATE pg_catalog."default",
    itemlocationline1_lotnumbers character varying COLLATE pg_catalog."default",
    itemlocationline1_lotsizingmethod character varying COLLATE pg_catalog."default",
    costestimatetype character varying COLLATE pg_catalog."default",
    costestimate character varying COLLATE pg_catalog."default",
    minimumquantity character varying COLLATE pg_catalog."default",
    enforceminqtyinternally character varying COLLATE pg_catalog."default",
    itempriceline1_itempricetyperef character varying COLLATE pg_catalog."default",
    itempriceline1_itemprice character varying COLLATE pg_catalog."default",
    itempriceline1_quantitypricing character varying COLLATE pg_catalog."default",
    cogsaccount character varying COLLATE pg_catalog."default",
    incomeaccount character varying COLLATE pg_catalog."default",
    assetaccount character varying COLLATE pg_catalog."default",
    billpricevarianceacct character varying COLLATE pg_catalog."default",
    billqtyvarianceacct character varying COLLATE pg_catalog."default",
    billexchratevarianceacct character varying COLLATE pg_catalog."default",
    custreturnvarianceaccount character varying COLLATE pg_catalog."default",
    vendreturnvarianceaccount character varying COLLATE pg_catalog."default",
    taxschedule character varying COLLATE pg_catalog."default",
    product_id character varying COLLATE pg_catalog."default",
    internalid character varying COLLATE pg_catalog."default",
    filename character varying COLLATE pg_catalog."default",
    load_id character varying COLLATE pg_catalog."default",
    date_upload character varying COLLATE pg_catalog."default",
    uploaded_by character varying COLLATE pg_catalog."default",
    running_id character varying COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS etc.load_staging
    OWNER to "DUser";