INSERT INTO etc.products (filename, date_upload, uploaded_by,
                    external_id, item_id, display_name, item_name, item_number_name, 
                    vendor_name_code, sales_description, sales_packaging_unit, sale_qty_per_pack_unit, 
                    item_color, item_size, pcs_in_box, sqft_by_pcs_sheet, sqft_by_box, price_by_UOM, 
                    units_type, stock_unit, purchase_unit, sales_units, parent, subsidiary, 
                    include_children, department, "class", "location", costing_method, "cost", 
                    purchase_description, stock_description, match_bill_to_receipt, use_bins, 
                    supply_replenishment_method, alternate_demand_source_item, 
                    auto_preferred_stock_level, reorder_multiple, is_special_order_item, 
                    auto_reorder_point, auto_lead_time, lead_time, safety_stock_level, 
                    safety_stock_level_days, transfer_price, preferred_location, 
                    item_bin_number1, preferred_per_location, vendor1_name, vendor1_subsidiary, 
                    vendor1_preferred, vendor1_purchase_price, vendor1_schedule, vendor1_code, 
                    vendor2_name, vendor2_subsidiary, vendor2_preferred, 
                    vendor2_purchase_price, vendor2_code, item_location_line1_location, 
                    item_location_line1_default_return_cost, item_location_line1_preferred_stock_level, 
                    item_location_line1_reorder_print, item_location_line1_lot_numbers, 
                    item_location_line1_lot_sizing_numbers, cost_estimate_type, cost_estimate, 
                    minimum_quantity, enforce_qty_internally, item_price_line1_item_price_type_ref, 
                    item_price_line1_item_price, item_price_line1_quantity_pricing, cogs_account, income_account, asset_account, 
                    bill_price_variance_acct, bill_qty_variance_acct, bill_exch_variance_acct, 
                    cust_return_variance_account, vend_return_variance_account, tax_schedule) 
                    SELECT etc.sample_tbl_1.filename, etc.sample_tbl_1.date_upload::timestamp, etc.sample_tbl_1.uploaded_by,
                    etc.sample_tbl_1.external_id, etc.sample_tbl_1.item_id, etc.sample_tbl_1.display_name, etc.sample_tbl_1.item_name, etc.sample_tbl_1.item_number_name, 
                    etc.sample_tbl_1.vendor_name_code, etc.sample_tbl_1.sales_description, etc.sample_tbl_1.sales_packaging_unit, CASE WHEN etc.sample_tbl_1.sale_qty_per_pack_unit = '' THEN 0 ELSE etc.sample_tbl_1.sale_qty_per_pack_unit::float END, 
                    etc.sample_tbl_1.item_color, etc.sample_tbl_1.item_size, CASE WHEN etc.sample_tbl_1.pcs_in_box = '' THEN 0 ELSE etc.sample_tbl_1.pcs_in_box::numeric END, CASE WHEN etc.sample_tbl_1.sqft_by_pcs_sheet = '' THEN 0 ELSE etc.sample_tbl_1.sqft_by_pcs_sheet::float END, CASE WHEN etc.sample_tbl_1.sqft_by_box = '' THEN 0 ELSE etc.sample_tbl_1.sqft_by_box::float END, CASE WHEN etc.sample_tbl_1.price_by_UOM = '' THEN 0 ELSE etc.sample_tbl_1.price_by_UOM::float END, 
                    etc.sample_tbl_1.units_type, etc.sample_tbl_1.stock_unit, etc.sample_tbl_1.purchase_unit, etc.sample_tbl_1.sales_units, etc.sample_tbl_1.parent, etc.sample_tbl_1.subsidiary, 
                    etc.sample_tbl_1.include_children, etc.sample_tbl_1.department, CASE WHEN etc.sample_tbl_1.class = '' THEN 0 ELSE etc.sample_tbl_1.class::numeric END, etc.sample_tbl_1.location, etc.sample_tbl_1.costing_method, CASE WHEN etc.sample_tbl_1.cost = '' THEN 0 ELSE etc.sample_tbl_1.cost::float END, 
                    etc.sample_tbl_1.purchase_description, etc.sample_tbl_1.stock_description, etc.sample_tbl_1.match_bill_to_receipt, etc.sample_tbl_1.use_bins, 
                    etc.sample_tbl_1.supply_replenishment_method, etc.sample_tbl_1.alternate_demand_source_item, 
                    etc.sample_tbl_1.auto_preferred_stock_level, etc.sample_tbl_1.reorder_multiple, etc.sample_tbl_1.is_special_order_item, 
                    etc.sample_tbl_1.auto_reorder_point, etc.sample_tbl_1.auto_lead_time, etc.sample_tbl_1.lead_time, etc.sample_tbl_1.safety_stock_level, 
                    etc.sample_tbl_1.safety_stock_level_days, etc.sample_tbl_1.transfer_price, etc.sample_tbl_1.preferred_location, 
                    etc.sample_tbl_1.item_bin_number1, etc.sample_tbl_1.preferred_per_location, etc.sample_tbl_1.vendor1_name, CASE WHEN etc.sample_tbl_1.vendor1_subsidiary = '' THEN 0 ELSE etc.sample_tbl_1.vendor1_subsidiary::numeric END, 
                    etc.sample_tbl_1.vendor1_preferred, CASE WHEN etc.sample_tbl_1.vendor1_purchase_price = '' THEN 0 ELSE etc.sample_tbl_1.vendor1_purchase_price::float END, etc.sample_tbl_1.vendor1_schedule, etc.sample_tbl_1.vendor1_code, 
                    etc.sample_tbl_1.vendor2_name, CASE WHEN etc.sample_tbl_1.vendor2_subsidiary = '' THEN 0 ELSE etc.sample_tbl_1.vendor2_subsidiary::numeric END, etc.sample_tbl_1.vendor2_preferred, 
                    CASE WHEN etc.sample_tbl_1.vendor2_purchase_price = '' THEN 0 ELSE etc.sample_tbl_1.vendor2_purchase_price::float END, etc.sample_tbl_1.vendor2_code, etc.sample_tbl_1.item_location_line1_location, 
                    etc.sample_tbl_1.item_location_line1_default_return_cost, etc.sample_tbl_1.item_location_line1_preferred_stock_level, 
                    etc.sample_tbl_1.item_location_line1_reorder_print, etc.sample_tbl_1.item_location_line1_lot_numbers, 
                    CASE WHEN etc.sample_tbl_1.item_location_line1_lot_sizing_numbers = '' THEN 0 ELSE etc.sample_tbl_1.item_location_line1_lot_sizing_numbers::numeric END, etc.sample_tbl_1.cost_estimate_type, CASE WHEN etc.sample_tbl_1.cost_estimate = '' THEN 0 ELSE etc.sample_tbl_1.cost_estimate::float END, 
                    CASE WHEN etc.sample_tbl_1.minimum_quantity = '' THEN 0 ELSE etc.sample_tbl_1.minimum_quantity::numeric END, etc.sample_tbl_1.enforce_qty_internally, etc.sample_tbl_1.item_price_line1_item_price_type_ref, 
                    CASE WHEN etc.sample_tbl_1.item_price_line1_item_price = '' THEN 0 ELSE etc.sample_tbl_1.item_price_line1_item_price::float END, CASE WHEN etc.sample_tbl_1.item_price_line1_quantity_pricing = '' THEN 0 ELSE etc.sample_tbl_1.item_price_line1_quantity_pricing::numeric END, etc.sample_tbl_1.cogs_account, etc.sample_tbl_1.income_account, etc.sample_tbl_1.asset_account, 
                    etc.sample_tbl_1.bill_price_variance_acct, etc.sample_tbl_1.bill_qty_variance_acct, etc.sample_tbl_1.bill_exch_variance_acct, 
                    etc.sample_tbl_1.cust_return_variance_account, etc.sample_tbl_1.vend_return_variance_account, etc.sample_tbl_1.tax_schedule FROM etc.sample_tbl_1;

SELECT * FROM etc.products;

TRUNCATE etc.products RESTART IDENTITY;