INSERT INTO etc.products (filename, date_upload, uploaded_by,
                    external_id, item_id, display_name, item_name, item_number_name, 
                    vendor_name_code, sales_description, sales_packaging_unit, sale_qty_per_pack_unit, 
                    item_color, item_size, pcs_in_box, sqft_by_pcs_sheet, sqft_by_box, price_by_UOM, 
                    units_type, stock_unit, purchase_unit, sales_units, parent, subsidiary, 
                    include_children, department, "class", "location", costing_method, "cost", 
                    purchase_description, stock_description, match_bill_to_receipt, use_bins, 
                    supply_replenishment_method, alternate_demand_source_item, 
                    auto_preferred_stock_level, reorder_multiple, is_special_order_item, 
                    auto_reorder_point, auto_lead_time, lead_time, safety_stock_level, 
                    safety_stock_level_days, transfer_price, preferred_location, 
                    item_bin_number1, preferred_per_location, vendor1_name, vendor1_subsidiary, 
                    vendor1_preferred, vendor1_purchase_price, vendor1_schedule, vendor1_code, 
                    vendor2_name, vendor2_subsidiary, vendor2_preferred, 
                    vendor2_purchase_price, vendor2_code, item_location_line1_location, 
                    item_location_line1_default_return_cost, item_location_line1_preferred_stock_level, 
                    item_location_line1_reorder_print, item_location_line1_lot_numbers, 
                    item_location_line1_lot_sizing_numbers, cost_estimate_type, cost_estimate, 
                    minimum_quantity, enforce_qty_internally, item_price_line1_item_price_type_ref, 
                    item_price_line1_item_price, item_price_line1_quantity_pricing, cogs_account, income_account, asset_account, 
                    bill_price_variance_acct, bill_qty_variance_acct, bill_exch_variance_acct, 
                    cust_return_variance_account, vend_return_variance_account, tax_schedule) 
                    SELECT etc.staging.filename, etc.staging.date_upload::timestamp, etc.staging.uploaded_by,
                    etc.staging.external_id, etc.staging.item_id, etc.staging.display_name, etc.staging.item_name, etc.staging.item_number_name, 
                    etc.staging.vendor_name_code, etc.staging.sales_description, etc.staging.sales_packaging_unit, CASE WHEN etc.staging.sale_qty_per_pack_unit = '' THEN 0 ELSE etc.staging.sale_qty_per_pack_unit::float END, 
                    etc.staging.item_color, etc.staging.item_size, CASE WHEN etc.staging.pcs_in_box = '' THEN 0 ELSE etc.staging.pcs_in_box::numeric END, CASE WHEN etc.staging.sqft_by_pcs_sheet = '' THEN 0 ELSE etc.staging.sqft_by_pcs_sheet::float END, CASE WHEN etc.staging.sqft_by_box = '' THEN 0 ELSE etc.staging.sqft_by_box::float END, CASE WHEN etc.staging.price_by_UOM = '' THEN 0 ELSE etc.staging.price_by_UOM::float END, 
                    etc.staging.units_type, etc.staging.stock_unit, etc.staging.purchase_unit, etc.staging.sales_units, etc.staging.parent, etc.staging.subsidiary, 
                    etc.staging.include_children, etc.staging.department, CASE WHEN etc.staging.class = '' THEN 0 ELSE etc.staging.class::numeric END, etc.staging.location, etc.staging.costing_method, CASE WHEN etc.staging.cost = '' THEN 0 ELSE etc.staging.cost::float END, 
                    etc.staging.purchase_description, etc.staging.stock_description, etc.staging.match_bill_to_receipt, etc.staging.use_bins, 
                    etc.staging.supply_replenishment_method, etc.staging.alternate_demand_source_item, 
                    etc.staging.auto_preferred_stock_level, etc.staging.reorder_multiple, etc.staging.is_special_order_item, 
                    etc.staging.auto_reorder_point, etc.staging.auto_lead_time, etc.staging.lead_time, etc.staging.safety_stock_level, 
                    etc.staging.safety_stock_level_days, etc.staging.transfer_price, etc.staging.preferred_location, 
                    etc.staging.item_bin_number1, etc.staging.preferred_per_location, etc.staging.vendor1_name, CASE WHEN etc.staging.vendor1_subsidiary = '' THEN 0 ELSE etc.staging.vendor1_subsidiary::numeric END, 
                    etc.staging.vendor1_preferred, CASE WHEN etc.staging.vendor1_purchase_price = '' THEN 0 ELSE etc.staging.vendor1_purchase_price::float END, etc.staging.vendor1_schedule, etc.staging.vendor1_code, 
                    etc.staging.vendor2_name, CASE WHEN etc.staging.vendor2_subsidiary = '' THEN 0 ELSE etc.staging.vendor2_subsidiary::numeric END, etc.staging.vendor2_preferred, 
                    CASE WHEN etc.staging.vendor2_purchase_price = '' THEN 0 ELSE etc.staging.vendor2_purchase_price::float END, etc.staging.vendor2_code, etc.staging.item_location_line1_location, 
                    etc.staging.item_location_line1_default_return_cost, etc.staging.item_location_line1_preferred_stock_level, 
                    etc.staging.item_location_line1_reorder_print, etc.staging.item_location_line1_lot_numbers, 
                    CASE WHEN etc.staging.item_location_line1_lot_sizing_numbers = '' THEN 0 ELSE etc.staging.item_location_line1_lot_sizing_numbers::numeric END, etc.staging.cost_estimate_type, CASE WHEN etc.staging.cost_estimate = '' THEN 0 ELSE etc.staging.cost_estimate::float END, 
                    CASE WHEN etc.staging.minimum_quantity = '' THEN 0 ELSE etc.staging.minimum_quantity::numeric END, etc.staging.enforce_qty_internally, etc.staging.item_price_line1_item_price_type_ref, 
                    CASE WHEN etc.staging.item_price_line1_item_price = '' THEN 0 ELSE etc.staging.item_price_line1_item_price::float END, CASE WHEN etc.staging.item_price_line1_quantity_pricing = '' THEN 0 ELSE etc.staging.item_price_line1_quantity_pricing::numeric END, etc.staging.cogs_account, etc.staging.income_account, etc.staging.asset_account, 
                    etc.staging.bill_price_variance_acct, etc.staging.bill_qty_variance_acct, etc.staging.bill_exch_variance_acct, 
                    etc.staging.cust_return_variance_account, etc.staging.vend_return_variance_account, etc.staging.tax_schedule FROM etc.staging;

SELECT * FROM etc.products;

TRUNCATE etc.products RESTART IDENTITY;